### ISSUE TITLE
Not able to distinguish first retry on external task from the last one

### ISSUE THREAD

**Issue by CezaryTarnowski-TomTom** [citilinkru/camunda-client-go#35]
Since the lib is using int type for the 'retries' field it is not possible to understand the difference between 'null' and '0'

I've created a PR to solve that:
https://github.com/citilinkru/camunda-client-go/pull/34

**Comment by mlaflamm** [comment]
I almost proposed the same change last week. I am still relatively new to Camunda but after reading about external tasks retry behavior and experimenting a bit, I have concluded that this is not necessary for our situation. 

With external tasks, you have to manage the retry count yourself, Camunda won't decrement it for you. With that knowledge, we decided to use `Retries` not as the number of retry left to execute but as the number of retry attempts i.e. incrementing the value instead of decrementing it. When you reach your max retry count, you send `Retries=0` to Camunda and your external task won't be retried. You can easily use the `Retries` value "as is" to compute an exponential backoff timeout.

~If you still want a decrementing behavior, you can verify if the previous `ErrorMessage` is empty or not.~ Edit: This may not work if you want to start another round of retries but this is a non-issue with an incrementing behavior.

I hope this is helpful.

**Comment by CezaryTarnowski-TomTom** [comment]
Indeed by incrementing the retries counter you can achieve working retries, nevertheless the documentation clearly states that:

> retries | Number | The number of retries the task currently has left.

To work with retries in a decreasing manner one needs to distinguish null from 0.

I believe that this change is aligned with the documentation of both the library and camunda. Therefore I still see value in having it introduced.

I see a risk in working in incremented retries mode that one day, with a new release, camunda may change the behavior and start to decrement the counter or have some other logic implemented based on the assumption that retries are decreasing.

**Comment by liderman** [comment]
@CezaryTarnowski-TomTom 
documentation example says that "retries" can be "null":
https://docs.camunda.org/manual/7.16/reference/rest/external-task/fetch/#response-2

Thanks for fix.
I merged PR.
